// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Programación_Web_Nubit.Context;

namespace Programación_Web_Nubit.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221127155731_Bd_nubit_web")]
    partial class Bd_nubit_web
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Programación_Web_Nubit.Models.Datos_academicos", b =>
                {
                    b.Property<int>("PkDatosacademicos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("especialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gradoegresado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombrescuela")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkDatosacademicos");

                    b.ToTable("Datos_academicos");
                });

            modelBuilder.Entity("Programación_Web_Nubit.Models.Datos_domicilio", b =>
                {
                    b.Property<int>("Pkdatosdomicilio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pkdatosdomicilio");

                    b.ToTable("Datos_Domicilios");
                });

            modelBuilder.Entity("Programación_Web_Nubit.Models.Datos_laborales", b =>
                {
                    b.Property<int>("Pkdatoslaborales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombrempresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lugartrabajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("puestoempeñado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiempoprestado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pkdatoslaborales");

                    b.ToTable("Datos_laborales");
                });

            modelBuilder.Entity("Programación_Web_Nubit.Models.Datos_personales", b =>
                {
                    b.Property<int>("Pkdatospersonales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechadenacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nacionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pkdatospersonales");

                    b.ToTable("datos_Personales");
                });

            modelBuilder.Entity("Programación_Web_Nubit.Models.Empleo", b =>
                {
                    b.Property<int>("Pk_empleo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto_servicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categorias")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pk_empleo");

                    b.ToTable("Empleo");
                });

            modelBuilder.Entity("Programación_Web_Nubit.Models.EmpleoXtrabajo", b =>
                {
                    b.Property<int>("PkEmpxTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Fk_empleo")
                        .HasColumnType("int");

                    b.Property<int>("Fk_trabajador")
                        .HasColumnType("int");

                    b.HasKey("PkEmpxTra");

                    b.HasIndex("Fk_empleo");

                    b.HasIndex("Fk_trabajador");

                    b.ToTable("EmpleoXtrabajos");
                });

            modelBuilder.Entity("Programación_Web_Nubit.Models.Perfil_de_trabajo", b =>
                {
                    b.Property<int>("PkPt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fk_rol")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkPt");

                    b.HasIndex("Fk_rol");

                    b.ToTable("Perfil_De_Trabajos");
                });

            modelBuilder.Entity("Programación_Web_Nubit.Models.Roles", b =>
                {
                    b.Property<int>("Pkrol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Asignacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pkrol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Programación_Web_Nubit.Models.Serviciosofrecidos", b =>
                {
                    b.Property<int>("Pkserofre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fk_empleo")
                        .HasColumnType("int");

                    b.HasKey("Pkserofre");

                    b.HasIndex("Fk_empleo");

                    b.ToTable("Serviciosofrecidos");
                });

            modelBuilder.Entity("Programación_Web_Nubit.Models.Trabajadores", b =>
                {
                    b.Property<int>("PkTrabajador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FkDatosacademicos")
                        .HasColumnType("int");

                    b.Property<int?>("FkPt")
                        .HasColumnType("int");

                    b.Property<int?>("Fkdatosdomicilio")
                        .HasColumnType("int");

                    b.Property<int?>("Fkdatoslaborales")
                        .HasColumnType("int");

                    b.Property<int?>("Fkdatospersonales")
                        .HasColumnType("int");

                    b.HasKey("PkTrabajador");

                    b.HasIndex("FkDatosacademicos");

                    b.HasIndex("FkPt");

                    b.HasIndex("Fkdatosdomicilio");

                    b.HasIndex("Fkdatoslaborales");

                    b.HasIndex("Fkdatospersonales");

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("Programación_Web_Nubit.Models.EmpleoXtrabajo", b =>
                {
                    b.HasOne("Programación_Web_Nubit.Models.Empleo", "empleo")
                        .WithMany()
                        .HasForeignKey("Fk_empleo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Programación_Web_Nubit.Models.Trabajadores", "trabajador")
                        .WithMany()
                        .HasForeignKey("Fk_trabajador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("empleo");

                    b.Navigation("trabajador");
                });

            modelBuilder.Entity("Programación_Web_Nubit.Models.Perfil_de_trabajo", b =>
                {
                    b.HasOne("Programación_Web_Nubit.Models.Roles", "roles")
                        .WithMany()
                        .HasForeignKey("Fk_rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roles");
                });

            modelBuilder.Entity("Programación_Web_Nubit.Models.Serviciosofrecidos", b =>
                {
                    b.HasOne("Programación_Web_Nubit.Models.Empleo", "serviciosofrecidos")
                        .WithMany()
                        .HasForeignKey("Fk_empleo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("serviciosofrecidos");
                });

            modelBuilder.Entity("Programación_Web_Nubit.Models.Trabajadores", b =>
                {
                    b.HasOne("Programación_Web_Nubit.Models.Datos_academicos", "datos_academicos")
                        .WithMany()
                        .HasForeignKey("FkDatosacademicos");

                    b.HasOne("Programación_Web_Nubit.Models.Perfil_de_trabajo", "perfil_de_trabajo")
                        .WithMany()
                        .HasForeignKey("FkPt");

                    b.HasOne("Programación_Web_Nubit.Models.Datos_domicilio", "datos_domicilio")
                        .WithMany()
                        .HasForeignKey("Fkdatosdomicilio");

                    b.HasOne("Programación_Web_Nubit.Models.Datos_laborales", "datos_laborales")
                        .WithMany()
                        .HasForeignKey("Fkdatoslaborales");

                    b.HasOne("Programación_Web_Nubit.Models.Datos_personales", "datos_personales")
                        .WithMany()
                        .HasForeignKey("Fkdatospersonales");

                    b.Navigation("datos_academicos");

                    b.Navigation("datos_domicilio");

                    b.Navigation("datos_laborales");

                    b.Navigation("datos_personales");

                    b.Navigation("perfil_de_trabajo");
                });
#pragma warning restore 612, 618
        }
    }
}
